### ISSUE TITLE
Missing property in parent pom

### ISSUE THREAD

**Issue by mathiasmaerker** [mstahv/sap-hana-with-vaadin#2]
cloud.sdk.version property missing in parent pom.xml

**Comment by mstahv** [comment]
Hi, did you try with a profile that defines the property and some other SAP HANA Cloud related stuff like suggested in the README.md ?

**Comment by mathiasmaerker** [comment]
Yes, no problem there, i just thought defining it in the parent pom would be a more easy setup for people to follow the blog..
